# Generated by Django 3.2.9 on 2023-11-20 19:46

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Modificado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('deb', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre9', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre11', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cre12', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Máquina de cartão',
                'verbose_name_plural': 'Máquinas de cartão',
            },
        ),
    ]
