# Generated by Django 4.2.7 on 2023-11-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="amount",
            new_name="value",
        ),
    ]
