# Generated by Django 3.2.9 on 2023-11-20 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Modificado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('description', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('1', 'CONTA DE ENERGIA'), ('2', 'CONTA DE AGUÁ'), ('3', 'CONTA DE INTERNET'), ('4', 'SALÁRIO FUNCIONÁRIO'), ('5', 'PAGAMENTO FORNECEDOR'), ('6', 'IMPOSTOS E TRIBUTOS')], max_length=5, verbose_name='Categorias')),
                ('status', models.CharField(choices=[('pay', 'Pago'), ('not_pay', 'A Pagar')], default='not_pay', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Conta a pagar',
                'verbose_name_plural': 'Contas a pagar',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BillsReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Modificado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('description', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('1', 'DOAÇÃO'), ('2', 'CONTA DE AGUÁ'), ('3', 'CONTA DE INTERNET'), ('4', 'SALÁRIO FUNCIONÁRIO'), ('5', 'PAGAMENTO FORNECEDOR'), ('6', 'IMPOSTOS E TRIBUTOS')], max_length=5, verbose_name='Categorias')),
                ('status', models.CharField(choices=[('pay', 'Recebido'), ('not_received', 'A Receber')], default='not_received', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Conta a receber',
                'verbose_name_plural': 'Contas a receber',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Modificado em')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('type', models.CharField(choices=[(0, 'saida'), (1, 'entrada')], max_length=2, verbose_name='TIPO')),
                ('id_object', models.CharField(blank=True, max_length=16, null=True)),
                ('movement', models.CharField(choices=[('to_pay', 'para pagar (pg)'), ('to_receive', 'para receber (pg)'), ('sale', 'Venda'), ('expenses', 'Despesas'), ('expenses', 'Despesas')], max_length=50)),
                ('detail_movement', models.CharField(max_length=35)),
                ('form_pg', models.CharField(choices=[('1', 'ESPECIE'), ('2', 'PIX'), ('3', 'CARTAO'), ('4', 'ESPECIE E PIX'), ('5', 'ESPECIE E CARTÃO'), ('6', 'PIX E CARTÃO'), ('7', 'ESPECIE, PIX E CARTÃO')], max_length=50, verbose_name='Forma de pagamento')),
                ('val_card', models.DecimalField(decimal_places=2, max_digits=6)),
                ('val_card_liq', models.DecimalField(decimal_places=2, max_digits=6)),
                ('val_pix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('val_money', models.DecimalField(decimal_places=2, max_digits=6)),
                ('val_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendendor')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
    ]
