# Generated by Django 4.2.7 on 2023-12-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_control", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billspay",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "Contas a Pagar/Receber",
                "verbose_name_plural": "Contas a Pagar/Receber",
            },
        ),
        migrations.AddField(
            model_name="movements",
            name="data_movement",
            field=models.JSONField(default=dict, verbose_name="Dados do Movimento"),
        ),
        migrations.AlterField(
            model_name="movements",
            name="movement",
            field=models.CharField(
                choices=[
                    ("to_pay", "para pagar (pg)"),
                    ("to_receive", "para receber (pg)"),
                    ("sale", "Venda"),
                    ("expenses", "Despesas"),
                ],
                max_length=50,
            ),
        ),
    ]
