# Generated by Django 4.2.7 on 2023-12-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "financial_control",
            "0002_alter_billspay_options_movements_data_movement_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="movements",
            name="movement",
            field=models.CharField(
                choices=[
                    ("account_paid", "Conta Paga"),
                    ("account_received", "Conta Recebida"),
                    ("sale", "Concluida Venda"),
                    ("expenses", "Despesas"),
                ],
                max_length=18,
            ),
        ),
        migrations.AlterField(
            model_name="movements",
            name="val_card",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="movements",
            name="val_card_liq",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="movements",
            name="val_money",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="movements",
            name="val_pix",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="movements",
            name="val_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
