# Generated by Django 4.2.7 on 2024-01-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_control", "0004_movement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movement",
            old_name="type",
            new_name="type_mov",
        ),
        migrations.RenameField(
            model_name="movements",
            old_name="type",
            new_name="type_mov",
        ),
    ]
