# Generated by Django 4.2.7 on 2024-01-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_control", "0006_alter_movements_type_mov"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Movement",
        ),
    ]
