# Generated by Django 4.2.7 on 2024-01-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_control", "0007_delete_movement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movements",
            name="type_mov",
            field=models.CharField(
                choices=[("0", "saida"), ("1", "entrada")],
                max_length=6,
                verbose_name="TIPO",
            ),
        ),
    ]
