# Generated by Django 4.2.7 on 2024-01-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_control", "0008_alter_movements_type_mov"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movements",
            old_name="data_movement",
            new_name="config_html",
        ),
        migrations.AlterField(
            model_name="movements",
            name="type_mov",
            field=models.CharField(
                choices=[("0", "Saida"), ("1", "Entrada")],
                max_length=6,
                verbose_name="TIPO",
            ),
        ),
    ]
